AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Questo template crea un utente IAM con permessi specifici per lavorare con Cloud9, EKS, Docker, 
  e Amazon ECR, crea un ambiente Cloud9 associato a questo utente e crea un repository AWS CodeCommit.

Parameters:
  UserName:
    Description: Il nome dell'utente IAM da creare e collegare all'ambiente Cloud9
    Type: String
  InstanceType:
    Description: Tipo di istanza EC2 per l'ambiente Cloud9
    Type: String
    Default: t3.micro
    AllowedValues:
      - t3.micro
      - t2.small
      - t2.medium
  AutomaticStopTime:
    Description: Tempo di spegnimento automatico in minuti
    Type: Number
    Default: 60
  UserPassword:
    Description: Password per l'utente IAM
    Type: String
    NoEcho: true
    Default: "Recube_workshop1"
  RepositoryName:
    Description: Il nome del repository CodeCommit da creare
    Type: String

Resources:

  IAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
      LoginProfile:
        Password: !Ref UserPassword
        PasswordResetRequired: True
      Policies:
        - PolicyName: CombinedCloud9UserPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - elasticloadbalancing:*
                  - ec2:*
                  - s3:*
                  - iam:*
                  - cloud9:*
                  - eks:*
                  - ecr:*
                  - codecommit:*
                  - ecs:*
                  - logs:*
                  - cloudwatch:*
                  - autoscaling:CreateLaunchConfiguration
                Resource: '*'


  Cloud9Environment:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties: 
      AutomaticStopTimeMinutes: !Ref AutomaticStopTime
      Description: !Sub "${UserName}'s Cloud9 environment"
      InstanceType: !Ref InstanceType
      Name: !Ref UserName
      OwnerArn: !GetAtt IAMUser.Arn
      ImageId: "amazonlinux-2023-x86_64"

  CodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      RepositoryDescription: !Sub "Repository for ${UserName}'s Cloud9 environment"

Outputs:
  UserArn:
    Description: L'ARN dell'utente IAM creato
    Value: !GetAtt IAMUser.Arn
  Password:
    Description: Password di accesso all'account provvisoria
    Value: !Ref UserPassword
  ConsoleSignInLink:
    Description: "Console sign-in link for the IAM user"
    Value: !Sub "https://${AWS::AccountId}.signin.aws.amazon.com/console/"
  RepositoryCloneUrlHttp:
    Description: URL per clonare il repository tramite HTTP
    Value: !GetAtt CodeCommitRepository.CloneUrlHttp
  RepositoryCloneUrlSsh:
    Description: URL per clonare il repository tramite SSH
    Value: !GetAtt CodeCommitRepository.CloneUrlSsh
  RepositoryArn:
    Description: ARN del repository CodeCommit
    Value: !GetAtt CodeCommitRepository.Arn
